# Generated by Django 5.2.5 on 2025-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncEventResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата синхронизации"
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Синхронизируемая дата"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("date", "By Date"), ("all", "All")],
                        max_length=10,
                        verbose_name="Тип синхронизации",
                    ),
                ),
                (
                    "new_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество новых событий"
                    ),
                ),
                (
                    "updated_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество обновленных событий"
                    ),
                ),
            ],
        ),
    ]
