# Generated by Django 5.2.5 on 2025-08-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="events.place",
                verbose_name="Место проведения",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                verbose_name="Статус мероприятия",
            ),
        ),
    ]
