# Generated by Django 5.2.5 on 2025-08-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
